/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genxium_ndkprac_NativeWrapper */

#ifndef _Included_com_genxium_ndkprac_NativeWrapper
#define _Included_com_genxium_ndkprac_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_genxium_ndkprac_NativeWrapper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_genxium_ndkprac_NativeWrapper_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_genxium_ndkprac_NativeWrapper
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_genxium_ndkprac_NativeWrapper_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
